# code: language=ansible
---
- name: Install minikube {{ minikube_version }}
  hosts: localhost
  gather_facts: false
  vars_files: vars.yaml
  vars_prompt:
    - name: sudo_pass
      prompt: "Provide your sudo password to start the installation"

  tasks:
    - name: Download minikube
      become: true
      ansible.builtin.get_url:
        url: "https://github.com/kubernetes/minikube/releases/download/{{ minikube_version }}/minikube-linux-amd64"
        dest: /usr/local/bin/minikube
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: root

    - name: Get minikube version
      ansible.builtin.command: minikube version
      register: minikube_cli

    - name: Verify that specified version == installed version
      ansible.builtin.assert:
        that: minikube_version in minikube_cli.stdout
        fail_msg: "Something went wrong. Use the deinstall.yaml playbook to cleanup and re-run this playbook for a fresh setup."
        success_msg: "minikube {{ minikube_version }} was installed successfully."

    - name: Ensure docker is started
      become: true
      ansible.builtin.systemd:
        name: docker.service
        state: started
      register: docker_state
      until: docker_state.status.ActiveState == "active"

    - name: Get minikube status
      ansible.builtin.command: minikube status
      ignore_errors: true
      register: minikube_status

    - name: Start minikube
      when: '"host: Running" not in minikube_status.stdout'
      ansible.builtin.command: minikube start

    - name: Setup minikube kubectl
      ansible.builtin.command: minikube kubectl get pods

    - name: Ensure bash-completion is installed
      become: true
      ansible.builtin.package:
        name: bash-completion

    - name: Get minikube bash completion output
      ansible.builtin.command: minikube completion bash
      register: minikube_bash_completion

    - name: Create minikube bash completion file
      become: true
      ansible.builtin.blockinfile:
        path: /usr/local/etc/bash_completion.d/minikube-completion
        create: true
        owner: "{{ ansible_user }}"
        group: root
        mode: "0755"
        block: "{{ minikube_bash_completion.stdout }}"

    - name: Create alias for "minikube kubectl"
      become: true
      ansible.builtin.blockinfile:
        path: /etc/profile.d/minikube.sh
        create: true
        owner: "{{ ansible_user }}"
        group: root
        mode: "0755"
        block: |
          alias minik='minikube kubectl --'

    - name: Add minikube to autostart
      when: minikube_autostart
      block:
        - name: Add docker.service to autostart, because minikube depends on it
          become: true
          ansible.builtin.systemd:
            name: docker.service
            enabled: true

        - name: Create systemd conf for minikube.service
          become: true
          ansible.builtin.blockinfile:
            path: /etc/systemd/system/minikube.service
            create: true
            owner: "{{ ansible_user }}"
            group: root
            mode: "0755"
            block: |
              [Unit]
              Description=Start minikube
              After=docker.service

              [Service]
              Type=oneshot
              ExecStart=/usr/local/bin/minikube start
              ExecStop=/usr/local/bin/minikube stop
              RemainAfterExit=true
              StandardOutput=journal
              User={{ ansible_user }}
              Group={{ ansible_user }}

              [Install]
              WantedBy=multi-user.target

        - name: Add minikube.service to autostart
          become: true
          ansible.builtin.systemd:
            name: minikube.service
            enabled: true
